'use strict';
const $=id=>document.getElementById(id),colors=['#f4acb7','#f0cb7a','#89d7d0','#c4b3f4'],names=['C4','E4','G4','C5'];
const example=[[0,4,8,12],[2,6,10,14],[0,7,8,15],[3,11]],defaultPattern=()=>example.map(row=>Array.from({length:16},(_,i)=>row.includes(i)));let pattern=defaultPattern(),source=null,audio=null,gain=null,cache=null,playVersion=0;
function tell(s){$('status').textContent=s;}
function stop(){playVersion++;if(source){source.onended=null;try{source.stop();}catch{}source.disconnect();source=null;}if(gain){gain.disconnect();gain=null;}$('stop').disabled=true;$('play').disabled=false;}
function draw(){const c=$('orbit'),x=c.getContext('2d');x.fillStyle='#263b73';x.fillRect(0,0,800,800);for(let row=0;row<4;row++){const rad=115+row*65;x.beginPath();x.arc(400,400,rad,0,Math.PI*2);x.strokeStyle='#7284b2';x.lineWidth=1;x.stroke();for(let col=0;col<16;col++){const angle=col*Math.PI/8-Math.PI/2,a=400+Math.cos(angle)*rad,b=400+Math.sin(angle)*rad;x.beginPath();x.arc(a,b,pattern[row][col]?10:3,0,Math.PI*2);x.fillStyle=pattern[row][col]?colors[row]:'#6679aa';x.fill();}}x.fillStyle='#eef0fb';x.font='20px Georgia,serif';x.textAlign='center';x.fillText('ORBIT / '+$('tempo').value+' BPM',400,398);x.font='14px sans-serif';x.fillText('4 VOICES · 16 STEPS',400,426);}
function edit(){stop();cache=null;draw();tell('节拍已更新。点击试听听取新版；尚未保存。');}
function grid(){const root=$('steps');root.replaceChildren();for(let row=0;row<4;row++){const label=document.createElement('span');label.className='rowlabel';label.textContent=names[row];root.append(label);for(let col=0;col<16;col++){const b=document.createElement('button');b.className='step';b.style.setProperty('--note',colors[row]);b.setAttribute('aria-label',names[row]+' 第'+(col+1)+'步');b.setAttribute('aria-pressed',String(pattern[row][col]));b.onclick=()=>{pattern[row][col]=!pattern[row][col];b.setAttribute('aria-pressed',String(pattern[row][col]));edit();};root.append(b);}}}
function data(){return cache??(cache=OrbitSound.make(pattern,Number($('tempo').value)));}
$('tempo').oninput=()=>{$('tempoValue').value=$('tempo').value;edit();};$('volume').oninput=()=>{$('volumeValue').value=$('volume').value;if(gain&&audio)gain.gain.setTargetAtTime(Number($('volume').value)/100,audio.currentTime,.03);};
$('play').onclick=async()=>{stop();const token=playVersion;$('play').disabled=true;try{audio??=new AudioContext();await audio.resume();if(token!==playVersion)return;const d=data(),buf=audio.createBuffer(1,d.pcm.length,d.rate);buf.copyToChannel(d.pcm,0);source=audio.createBufferSource();source.buffer=buf;gain=audio.createGain();gain.gain.value=Number($('volume').value)/100;source.connect(gain);gain.connect(audio.destination);source.onended=()=>{if(token!==playVersion)return;stop();tell('试听结束，可修改或导出。');};source.start();$('stop').disabled=false;tell('正在试听约 '+d.duration.toFixed(1)+' 秒；随时可停止。');}catch(e){stop();tell('无法启用音频：'+e.message+'。仍可尝试导出WAV。');}};
$('stop').onclick=()=>{stop();tell('已停止。');};
function download(blob,name){const url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),5000);}
$('wav').onclick=()=>{try{const d=data();download(new Blob([OrbitSound.wav(d.pcm,d.rate)],{type:'audio/wav'}),'orbit-beats.wav');tell('已请求保存WAV，固定合成音量；播放文件前请调低设备音量。');}catch(e){tell('导出失败：'+e.message);}};
$('png').onclick=()=>$('orbit').toBlob(b=>{if(b)download(b,'orbit-beats.png');},'image/png');
$('clear').onclick=()=>{if(!confirm('清空全部节拍？'))return;pattern=Array.from({length:4},()=>Array(16).fill(false));grid();edit();};$('reset').onclick=()=>{if(!confirm('恢复示例，替换当前节拍？'))return;pattern=defaultPattern();grid();edit();};$('new').onclick=()=>{if(!confirm('用随机节拍替换当前编辑？'))return;const a=new Uint32Array(64);crypto.getRandomValues(a);pattern=Array.from({length:4},(_,r)=>Array.from({length:16},(_,c)=>a[r*16+c]%5===0));grid();edit();};
window.addEventListener('pagehide',()=>{stop();const retiring=audio;audio=null;if(retiring&&retiring.state!=='closed')retiring.close().catch(()=>{});});grid();draw();
