const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),{pathToFileURL}=require('node:url'),P=require('./project.js'),{chromium}=require(process.env.PLAYWRIGHT_MODULE||'playwright');
const checks=[],base={format:'orbit-beats-project',version:1,tempo:104,volume:15,pattern:Array.from({length:4},(_,r)=>Array.from({length:16},(_,c)=>(c+r)%3===0))};
assert.deepEqual(P.parse(P.serialize({tempo:base.tempo,volume:base.volume,pattern:base.pattern})),base);assert.deepEqual(P.parse('\uFEFF'+JSON.stringify(base)),base);const copy=P.validate(base);copy.pattern[0][0]=!copy.pattern[0][0];assert.notDeepEqual(copy.pattern,base.pattern);checks.push('Project round trip, BOM handling and detached pattern copy');
for(const patch of [{tempo:Infinity},{tempo:60.5},{volume:51},{volume:-1},{version:2},{format:'other'},{pattern:[]},{extra:'x'}])assert.throws(()=>P.validate({...base,...patch}));assert.throws(()=>P.parse('['));assert.throws(()=>P.parse(' '.repeat(8193)));assert.throws(()=>P.parse(JSON.stringify(base).slice(0,-1)+',"__proto__":{"polluted":true}}'));const sparse=Array(4);assert.throws(()=>P.validate({...base,pattern:sparse}));assert.equal({}.polluted,undefined);checks.push('Schema bounds, unknown/prototype fields, sparse matrix and malformed JSON rejected');
(async()=>{const out=path.join(__dirname,'test-output');fs.mkdirSync(out,{recursive:true});const b=await chromium.launch(),ctx=await b.newContext({acceptDownloads:true,viewport:{width:1440,height:1100}});await ctx.setOffline(true);const p=await ctx.newPage(),errors=[],requests=[];p.on('pageerror',e=>errors.push(e.message));p.on('request',r=>{if(/^https?:/.test(r.url()))requests.push(r.url());});let accept=true;p.on('dialog',d=>accept?d.accept():d.dismiss());await p.goto(pathToFileURL(path.join(__dirname,'index.html')).href);
const snapshot=()=>p.evaluate(()=>({tempo:Number(document.getElementById('tempo').value),volume:Number(document.getElementById('volume').value),pattern:Array.from(document.querySelectorAll('.step'),b=>b.getAttribute('aria-pressed')==='true')}));
async function load(data,name='example.json'){await p.locator('#loadProject').setInputFiles({name,mimeType:'application/json',buffer:Buffer.from(typeof data==='string'?data:JSON.stringify(data))});await p.waitForFunction(()=>!document.getElementById('loadProject').disabled);}
await p.locator('.step').first().click();await p.locator('#tempo').fill('120');const before=await snapshot();const dl=p.waitForEvent('download');await p.click('#saveProject');const saved=path.join(out,'saved-project.json');await(await dl).saveAs(saved);const data=P.parse(fs.readFileSync(saved,'utf8'));assert.equal(data.tempo,120);assert.deepEqual(data.pattern.flat(),before.pattern);await p.click('#clear');await load(data);assert.deepEqual(await snapshot(),before);assert.equal(await p.locator('#stop').isDisabled(),true);checks.push('Actual saved JSON downloaded, validated and loaded: exact UI round trip, no autoplay');
accept=false;await load(base);assert.deepEqual(await snapshot(),before);accept=true;for(const invalid of ['{bad',JSON.stringify({...base,version:9}),'x'.repeat(8193)]){await load(invalid);assert.deepEqual(await snapshot(),before);assert.match(await p.locator('#status').textContent(),/载入失败/);}await load(base,'fake.exe');assert.deepEqual(await snapshot(),before);checks.push('Cancelled, malformed, unsupported, oversized and wrong-extension imports preserve current state');
await p.click('#play');await p.waitForFunction(()=>!document.getElementById('stop').disabled);await load(base);assert.equal(await p.locator('#stop').isDisabled(),true);assert.equal((await snapshot()).tempo,104);checks.push('Successful import stops old playback and replaces controls atomically');
// Controlled slow file read to verify that edits cannot be overwritten by an old async import.
await p.evaluate(()=>{const original=File.prototype.text;File.prototype.text=async function(){await new Promise(r=>setTimeout(r,200));return original.call(this);};});await p.locator('#loadProject').setInputFiles({name:'slow.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify(data))});await p.locator('.step').first().click();const edited=await snapshot();await p.waitForFunction(()=>!document.getElementById('loadProject').disabled);assert.deepEqual(await snapshot(),edited);assert.match(await p.locator('#status').textContent(),/编排已变化/);checks.push('Delayed import cannot overwrite intervening edits');
await p.screenshot({path:path.join(out,'project-desktop.png'),fullPage:true});await p.setViewportSize({width:390,height:844});assert.equal(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);assert.deepEqual(errors,[]);assert.deepEqual(requests,[]);assert.deepEqual(await p.evaluate(()=>[localStorage.length,sessionStorage.length]),[0,0]);checks.push('Narrow layout, no page errors, offline zero HTTP and no persistence');fs.writeFileSync(path.join(out,'project-results.json'),JSON.stringify({timestamp:new Date().toISOString(),browser:await b.version(),status:'PASS',checks,errors,requests},null,2));console.log(checks);await b.close();})().catch(e=>{console.error(e);process.exit(1)});
